global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'dotnet_api-region'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-region:8080']
  - job_name: 'dotnet_api-contact'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-contact:8080']      
